version: "3.7"

networks:
  web:
    driver: bridge
  internal:
    driver: bridge

services:
  api:
    container_name: vms_api
    build:
      context: ./api
    tty: true
    volumes:
      - ./api:/app
    networks:
      - internal
    env_file:
      - .env
    ports:
      - "8000:8000"

  zmq:
    container_name: vms_zmq
    build:
      context: ./zmq
    tty: true
    volumes:
      - ./zmq:/zmq
    networks:
      - internal
    ports:
      - "4444:4444"
    devices:
      - /dev/video0:/dev/video0

  adminer:
    container_name: vms_adminer
    image: adminer
    env_file:
      - .env
    networks:
      - internal

  nginx:
    container_name: vms_nginx
    image: "nginx:stable"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web
      - internal
    env_file:
      - .env
    depends_on:
      - adminer
      - api
